import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import ToastProdvider from "@/providers/toast-provider";

import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn("min-h-screen", font.className)}>
          <ToastProdvider />
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
